### ISSUE TITLE
Eye Tracker

### ISSUE THREAD

**Issue by danigallegdup** [danigallegdup/Numeric_Data_Table_Visual_Aid_Experiment#13]
Output .txt files, per task
- [x] Time and milisecond
- [x] Where the eyes are x and y cordinates
- [ ] Fixations times
- [ ] Vector movements of eye saccades
